name: CI/CD Pipeline

on:
  push:
    branches: [ "web" ]  
    paths:
      - 'backend/backend/**/*.java' 
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/backend/pom.xml') }}  # Cache based on backend POM
          restore-keys: ${{ runner.os }}-maven-

      - name: Build and Test with Maven
        working-directory: backend/backend  
        run: mvn clean package  

  deploy-to-main:
    needs: test-and-build  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: web 

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge web into main
        run: |
          git fetch origin main
          git checkout main
          git merge web --allow-unrelated-histories --no-edit  
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
